name: Trigger auto deployment for my-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - '**'
      - '.github/workflows/my-container-AutoDeployTrigger-78e01055-a8e9-4159-9d96-ed44ab4827da.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.x

      - name: Install dependencies
        run: pnpm install

      - name: Build NX app
        run: pnpm nx build api --prod

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: apps/api/Dockerfile # Update this to the correct Dockerfile path
          registryUrl: ghcr.io # e.g., myregistry.azurecr.io
          registryUsername: ${{ secrets.GH_USER }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}
          containerAppName: my-container
          resourceGroup: appsvc_linux_mexicocentral
          imageToBuild: ghcr.io/${{ secrets.GH_USER }}/my-nest-app:latest
          buildArguments: |
            NODE_ENV=production
